### ISSUE TITLE
Email response slot can't find by from.py

### ISSUE THREAD

**Issue by jimjimjimjimjimjimjimjimjim** [tienthanh214/googleform-autofill-and-submit#3]
I tried this awesome script to help me automate the Google form but it seems can't get the email response slot via `from.py` if the form holder requires the respondent's email. Does anyone know how to solve the issue?

**Comment by tienthanh214** [comment]
Thanks for the issue. I've just pushed a fix that adds the "emailAddress" field to the request body to address above problem 08d68baad2a007027d49092f6127a043cdf0bd56. Feel free to pull the latest changes and test it out.

**Comment by jimjimjimjimjimjimjimjimjim** [comment]
Thanks for your response!
